# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket       = "shopstream-tfstate-544234170512"
    encrypt      = true
    key          = "./terraform.tfstate"
    region       = "ca-central-1"
    use_lockfile = true
  }
}
