{{- if .Values.externalSecret.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "shopstream.fullname" . }}
  labels:
    {{- include "shopstream.labels" . | nindent 4 }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ include "shopstream.fullname" . }}-aws
    kind: SecretStore
  target:
    name: {{ .Values.secretName }}
    creationPolicy: Owner
    template:
      data:
        # Construct DATABASE_URL from the individual fields in the RDS managed secret JSON
        DATABASE_URL: "postgresql://{{ "{{" }} .username {{ "}}" }}:{{ "{{" }} .password {{ "}}" }}@{{ "{{" }} .host {{ "}}" }}:{{ "{{" }} .port {{ "}}" }}/{{ "{{" }} .dbname {{ "}}" }}"
        RAILS_MASTER_KEY: "{{ "{{" }} .rails_master_key {{ "}}" }}"
  data:
    - secretKey: username
      remoteRef:
        key: {{ .Values.externalSecret.rdsSecretArn }}
        property: username
    - secretKey: password
      remoteRef:
        key: {{ .Values.externalSecret.rdsSecretArn }}
        property: password
    - secretKey: host
      remoteRef:
        key: {{ .Values.externalSecret.rdsSecretArn }}
        property: host
    - secretKey: port
      remoteRef:
        key: {{ .Values.externalSecret.rdsSecretArn }}
        property: port
    - secretKey: dbname
      remoteRef:
        key: {{ .Values.externalSecret.rdsSecretArn }}
        property: dbname
    - secretKey: rails_master_key
      remoteRef:
        key: {{ .Values.externalSecret.railsMasterKeySecretName }}
{{- end }}
