{{- if .Values.externalSecret.enabled }}
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: {{ include "shopstream.fullname" . }}-aws
  labels:
    {{- include "shopstream.labels" . | nindent 4 }}
spec:
  provider:
    aws:
      service: SecretsManager
      region: {{ .Values.externalSecret.region }}
      auth:
        jwt:
          serviceAccountRef:
            name: external-secrets
            namespace: external-secrets
{{- end }}
