replicaCount: 1

ingress:
  enabled: true
  scheme: internal

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

secretName: shopstream-secrets

externalSecret:
  enabled: true
  region: ca-central-1
  rdsSecretArn: ""          # set at deploy time: --set externalSecret.rdsSecretArn=<arn>
  railsMasterKeySecretName: "shopstream/dev/rails-master-key"
